- name: register elasticsearch rpm key
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: install the repo file
  copy:
    src: "{{ item }}.repo"
    dest: /etc/yum.repos.d/{{ item }}.repo
  with_items:
  - logstash-forwarder

- name: install rpm packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - logstash-forwarder

- name: copy logstash server certificate
  copy:
    src: /etc/pki/tls/certs/logstash-forwarder.crt
    dest: /etc/pki/tls/certs/logstash-forwarder.crt

- name: copy the configuration file
  copy:
    src: logstash-forwarder.json
    dest: /etc/logstash-forwarder.json

- name: create supervisor config
  copy:
    src: logstash-forwarder.ini
    dest: /etc/supervisord.d/logstash-forwarder.ini
  register: supervisord

- name: reload supervisord
  shell: supervisorctl reload
  when: supervisord.changed
